services:
  - type: web
    name: ati-project-web
    env: docker
    repo: https://github.com/kiyotakapain/ati-project
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_URL
        value: https://ati-project.onrender.com
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite

  - type: worker
    name: ati-project-worker
    env: docker
    repo: https://github.com/kiyotakapain/ati-project
    branch: main
    dockerfilePath: Dockerfile
    startCommand: php artisan queue:work --sleep=3 --tries=3
